version: '3'
services:
    ad-dc:
        build: .
        stdin_open: true
        network_mode: "host"    
        hostname: "AD"
        privileged: true
        ports:
            - "53:53"
            - "53:53/udp"
            - "88:88"
            - "88:88/udp"
            - "135:135"
            - "137:137/udp"
            - "138:138/udp"
            - "139:139"
            - "389:389"
            - "389:389/udp"
            - "445:445"
            - "464:464"
            - "464:464/udp"
            - "636:636"
            - "49152:49200"
            - "3268:3268"
            - "3269:3269"
            - "123:123/udp"
        volumes:
            - /home/user/projects/dockerfiles/samba-ad-dc/samba:/var/lib/samba        
            - /home/user/projects/dockerfiles/samba-ad-dc/shares:/shares
            - /home/user/projects/dockerfiles/samba-ad-dc/ntp:/etc/ntp
            - /home/user/projects/dockerfiles/samba-ad-dc/logs:/var/log:rw
        environment:
            - SAMBA_REALM=kernel.consulting
            - SAMBA_DOMAIN=KERNEL
            - SAMBA_UID_START=1000
#will be created and printed if not set
            - SAMBA_PASSWORD=Test-123
            - SAMBA_HOST_IP=10.137.2.31
            - SAMBA_DNS_FORWARDER=10.137.2.1
        dns:
            - 10.137.2.31
            - 10.137.2.1
        dns_search:
            - kernel.consulting
        domainname: kernel.consulting

            
