version: '3'
services:
    ad-dc:
        build: .
        stdin_open: true
        network_mode: "host"    
        hostname: "AD"
        ports:
            - "53:53"
            - "53:53/udp"
            - "88:88"
            - "88:88/udp"
            - "135:135"
            - "137:137/udp"
            - "138:138/udp"
            - "139:139"
            - "389:389"
            - "389:389/udp"
            - "445:445"
            - "464:464"
            - "464:464/udp"
            - "636:636"
            - "49152:49200"
            - "3268:3268"
            - "3269:3269"
        volumes:
            - /home/user/projects/dockerfiles/samba-ad-dc/samba:/var/lib/samba        
            - /home/user/projects/dockerfiles/samba-ad-dc/shares:/shares
        environment:
            - SAMBA_REALM=this.local
#SAMBA_PASSWORD="Password1!"	#will be created and printed if not set
            - SAMBA_HOST_IP=10.137.2.29
            - SAMBA_DNS_FORWARDER=10.137.2.1
